### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by tirnovar** [microsoft/PowerBI-Icons#14]
Hello everyone,

thank you for your incredible work!
Here I am sending a list of icons that I think are missing here:

1) Workbook
2) Promoted badge
3) Certified badge
4) Calculation Groups
5) Streaming Dataflows

Kind regards
Štěpán Rešl

**Comment by marclelijveld** [comment]
I believe the workbook has the same icon as a dataset in the Power BI Service nowadays. But please correct me if I'm wrong @tirnovar

**Comment by marclelijveld** [comment]
Interesting.... I just uploaded a workbook in a new workspace, and it showed for me as a generic dataset. Let me try that again @tirnovar. Other than that, I just created [pull request 15](https://github.com/microsoft/PowerBI-Icons/pull/15) to add the streaming dataflow icon.

**Comment by marclelijveld** [comment]
Also added a (re-created) icon for workbooks now. There seems to be a difference in how you import the workbook. (import / connect). Created something like the Excel Workbook icon in the same matching style as all other icons and created [pull request 16](https://github.com/microsoft/PowerBI-Icons/pull/16) for that.

**Comment by jeroenterheerdt** [comment]
Added icons for #5 and #1: https://github.com/microsoft/PowerBI-Icons/commit/161023475b19f5cdba6835e2fcc24179fe87cc28.

**Comment by jeroenterheerdt** [comment]
#4 calculation groups are not supported in Desktop officially, so the icon was really chosen by TE or other external tools, so I cannot add an official icon for it. The badges (#2, #3) I am not sure if we can add those, they are not real icons..

**Comment by tirnovar** [comment]
Thank you so much for adding no1 & no5. I understand that no4 can't be counted. 
But no2 & no3 have their icons inside PBIS same "icons" are shown when I want to add Power BI Dataset to model in PBID.
<img width="148" alt="image" src="https://user-images.githubusercontent.com/78301524/145199055-141c73a6-c411-475f-bd8a-785c32f48738.png">

**Comment by jeroenterheerdt** [comment]
look what I found ;). Calc groups is the only one that does not have an official icon.

**Comment by tirnovar** [comment]
Absolutely awesome! I think we can close this issue 🤩
