### ISSUE TITLE
Table icon?

### ISSUE THREAD

**Issue by gdeckler** [microsoft/PowerBI-Icons#25]
Any chance there is just a straight Table icon?

**Comment by jeroenterheerdt** [comment]
which? do you have a screenshot of the icon and where it shows up?

**Comment by gdeckler** [comment]
Sure. 
![image](https://user-images.githubusercontent.com/14352511/166977046-3a2cde8f-eed8-44b2-ad56-a0a2f865daf8.png)

**Comment by jeroenterheerdt** [comment]
thanks, added. Can't believe we missed that one :)
