### ISSUE TITLE
fx icon

### ISSUE THREAD

**Issue by gdeckler** [microsoft/PowerBI-Icons#27]
Any chance we can get the fx icon added? Shows up in type ahead in DAX editor.
![image](https://user-images.githubusercontent.com/14352511/167059021-0684a45a-7d8e-446d-a69f-cc8fad243758.png)

**Comment by jeroenterheerdt** [comment]
here you go @gdeckler

**Comment by gdeckler** [comment]
Awesome! Thanks!

Gregory J. Deckler | LinkedIn<https://www.linkedin.com/in/gregdeckler> |Twitter<https://twitter.com/GregDeckler>
Vice President, Microsoft Cloud Practice
[A close up of a sign  Description automatically generated]Microsoft MVP, Power BI, 2016-2021



O/M: 614.558.3688
fusionalliance.com<https://fusionalliance.com/>
