### ISSUE TITLE
Power BI Cloud Image Request

### ISSUE THREAD

**Issue by swolfe2** [microsoft/PowerBI-Icons#29]
Hello!

When trying to create maps in Visio of my company's publishing platform, it would be really helpful to have an image similar to the Power BI Desktop one but for Power BI with a yellow cloud or something. That would help users understand the difference between actions that happen in Power BI Desktop vs. cloud service.

An example would be RLS implementation. Rules are created in Power BI Desktop, but people are assigned to those rules once the dataset has been published to a Workspace in the cloud service.

The cloud images I can find in Google Images use the old Power BI logo, and would love to have something official/current.

Thanks!

**Comment by marclelijveld** [comment]
Hi @swolfe2

There is a [specific icon for Power BI Desktop](https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/Desktop.png) as well as for [PBI Desktop for Report server](https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/DesktopRS.png). 
To my understanding the [generic Power BI](https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/Power-BI.png) icon we all know and love, is the one to be used for the Power BI Service. 

Cheers,
Marc

**Comment by swolfe2** [comment]
> Hi @swolfe2
> 
> There is a [specific icon for Power BI Desktop](https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/Desktop.png) as well as for [PBI Desktop for Report server](https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/DesktopRS.png). 
> To my understanding the [generic Power BI](https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/Power-BI.png) icon we all know and love, is the one to be used for the Power BI Service. 
> 
> Cheers,
> Marc

Thanks for the reply.

Unfortunately, it is not discernable by the average end user what the difference is between PBI Desktop and the PBI Service is, when it comes to an image that can be used in diagrams.

Creating a simple icon with a typical "cloud" shape would overcome this. We do this today, but it would be nice to have in official documentation.

**Comment by jeroenterheerdt** [comment]
closing this - there is no official icon.
