### ISSUE TITLE
Missing Datamart icon

### ISSUE THREAD

**Issue by tirnovar** [microsoft/PowerBI-Icons#30]
Hello guys,

I can already imagine how reluctant you are to see me opening a ticket for this repository: D but due to the addition of Datamarts to the world of Power BI. Would it be possible to add his icon here as well?

**Comment by jeroenterheerdt** [comment]
no worries, let me go find it and add it.

**Comment by marclelijveld** [comment]
Not everywhere though. If you look at a datamart in a workspace, it has a different icon than a datamart in a deployment pipeline at the moment. 

See examples below. 
![image](https://user-images.githubusercontent.com/38921736/173298719-3686210e-8883-4f77-ae35-05f17817382a.png)

![image](https://user-images.githubusercontent.com/38921736/173298748-ba241032-4e7f-466b-b8f7-6be5b591cb6c.png)

**Comment by tirnovar** [comment]
Seems that lineage view has old icon also :D 

<img width="758" alt="image" src="https://user-images.githubusercontent.com/78301524/173301403-b50ad57d-49f9-46b1-b529-f4315073cc91.png">

**Comment by tirnovar** [comment]
I have prepared the new icon O:) 

![Datamart](https://user-images.githubusercontent.com/78301524/173309517-2b09469a-5e86-4bc7-95aa-8ca924da322f.svg)

**Comment by jeroenterheerdt** [comment]
let's keep in mind that this is not the official icon. Still tracking it down.

**Comment by jeroenterheerdt** [comment]
just added the icon!

**Comment by tirnovar** [comment]
Thank you so much @jeroenterheerdt
