### ISSUE TITLE
Icons for Power Query Data Types

### ISSUE THREAD

**Issue by MiniKouign** [microsoft/PowerBI-Icons#42]
Data types icons are missing in your library
Found most of them from Microsoft on this page : https://learn.microsoft.com/en-us/power-query/data-types
But still, Table, List and Record icons where missing, so I did them myself, same specifications  (transparency, 20x20 png)
Sorry, don't have SVGs :-/
Files are attached to this issue, feel free to add them

Regards !

![PowerQueryTypeDate](https://user-images.githubusercontent.com/57835109/196199053-59542d67-97bc-4d17-989d-7992e7aac9c6.png)
![PowerQueryTypeDatetime](https://user-images.githubusercontent.com/57835109/196199057-3aa53b47-ffa7-4f5e-9f63-ca81ccdadfb7.png)
![PowerQueryTypeDatetimezone](https://user-images.githubusercontent.com/57835109/196199062-f50ffac6-df7c-4938-a1ee-1ede5ce3982a.png)
![PowerQueryTypeDuration](https://user-images.githubusercontent.com/57835109/196199066-b601b0fe-f0cc-4abb-9d44-606c2697500b.png)
![PowerQueryTypeList](https://user-images.githubusercontent.com/57835109/196199067-f8bf5065-f609-4ca3-8db0-162956bbfa6b.png)
![PowerQueryTypeLogical](https://user-images.githubusercontent.com/57835109/196199068-3c686b2b-4df5-4d3c-a979-c5f63e014e21.png)
![PowerQueryTypeNumber](https://user-images.githubusercontent.com/57835109/196199073-fd95589b-cf77-4d0f-b4f7-81aea9114177.png)
![PowerQueryTypePercentage](https://user-images.githubusercontent.com/57835109/196199077-7f481859-7b3c-4def-a4ea-75c1ece1cc3f.png)
![PowerQueryTypeRecord](https://user-images.githubusercontent.com/57835109/196199079-b5eec545-919a-4467-8136-911176f8116b.png)
![PowerQueryTypeTable](https://user-images.githubusercontent.com/57835109/196199080-2c9819de-60bc-4279-b3d6-2acff21dd78a.png)
![PowerQueryTypeText](https://user-images.githubusercontent.com/57835109/196199083-1d97bbe2-566f-497d-8d49-151b529719e7.png)
![PowerQueryTypeTime](https://user-images.githubusercontent.com/57835109/196199086-61bbbd6d-2641-466d-b34b-ae5020c20072.png)
![PowerQueryTypeWholenumber](https://user-images.githubusercontent.com/57835109/196199091-3198610b-56f1-4368-935e-87f31a02f7ea.png)
![PowerQueryTypeAny](https://user-images.githubusercontent.com/57835109/196199093-e6d432bb-1dc6-4cc4-b326-6b72f17101d4.png)
![PowerQueryTypeBinary](https://user-images.githubusercontent.com/57835109/196199096-a4897582-7975-4983-bd3f-55989662807a.png)
![PowerQueryTypeCurrency](https://user-images.githubusercontent.com/57835109/196199099-2feb9cb5-8eb4-4627-9199-6a32d4bd2251.png)

**Comment by jeroenterheerdt** [comment]
Thanks for opening the issue! I have added the Power Query icons. Note these are the new style as used in Power Query online.
