### ISSUE TITLE
Power BI Data Gateway Icon

### ISSUE THREAD

**Issue by daryl-lynch-bzy** [microsoft/PowerBI-Icons#46]
Hi - could you please add an icon the represents the Power BI data gateway.  I am thinking about the icons that Kurt has on his blob.

[https://data-goblins.com/gateway-checklist](url)

**Comment by marclelijveld** [comment]
There is a gateway icon in the repo similar to the one your referred to. You can find it in the PNG folder. 
https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/On-Premises-Data-Gateway.png
