### ISSUE TITLE
Missing (colored) Icons

### ISSUE THREAD

**Issue by SteffenSchramm** [microsoft/PowerBI-Icons#47]
Hi,
it is possible to provide the used icons on this sites:

- https://learn.microsoft.com/de-de/power-bi/guidance/powerbi-implementation-planning-usage-scenario-self-service-content-publishing
- https://learn.microsoft.com/de-de/power-bi/guidance/powerbi-implementation-planning-usage-scenario-advanced-data-model-management

e.g. model, workspace, premium, dataflow, ...

Thanks a lot

**Comment by marclelijveld** [comment]
Are the colored icons what you refer to @SteffenSchramm? Those are the old ones which are no longer used in the Power BI service. However, I had them on my GitHub first and you can still find them in [this archived repo](https://github.com/marclelijveld/Power-BI-Icons-Archived). 

--Marc

**Comment by SteffenSchramm** [comment]
Thanks for the link.
But what do you mean by "These are the old ones that are no longer used in Power BI"?
For example, when I open the Power BI service on the home screen (https://app.powerbi.com/home) or a workspace, the icons in front of the list items are colored. All => Report(blue), Dataset(orange), Dataflow(brown), ...

Thanks for reply
