### ISSUE TITLE
Power BI Service icon

### ISSUE THREAD

**Issue by mh-gd** [microsoft/PowerBI-Icons#5]
Very cool, almost all icons are now available, which helps a lot for architecture design.

For me, the only icon really missing now is the new one for the Power BI Service. Would be cool if that can be added soon!

**Comment by jeroenterheerdt** [comment]
not sure which icon you're looking for - do you have an example?

**Comment by mh-gd** [comment]
Yes, at [this picture](https://powerbiblogscdn.azureedge.net/wp-content/uploads/2021/02/new_icon_update.png) you can see the new icon for the Power BI Service. It is the very left one.

**Comment by jeroenterheerdt** [comment]
that's just listed as Power BI: https://github.com/microsoft/PowerBI-Icons/blob/main/PNG/PowerBI.png

**Comment by mh-gd** [comment]
ah I see, thanks for the hint!
