### ISSUE TITLE
New missing icons

### ISSUE THREAD

**Issue by tirnovar** [microsoft/PowerBI-Icons#54]
Name | Data-TestID | IMG
---- | ----------- | ---
Pipeline | artifact_data_pipeline_preview | ![Pipeline](https://github.com/microsoft/PowerBI-Icons/assets/78301524/3dbbff2c-5748-4eb0-96ce-003153e007a2)
Data Warehouse | artifact_warehouse_preview | ![Warehouse](https://github.com/microsoft/PowerBI-Icons/assets/78301524/6e54b006-5fad-408b-91c3-d41fa8f7ec0d)
Lakehouse | trident_artifacttype_lakehouse_preview | ![Lakehouse](https://github.com/microsoft/PowerBI-Icons/assets/78301524/49c42143-58cc-4ebb-bb8d-813c6b629902)
Notebook | notebook_preview | ![Notebook](https://github.com/microsoft/PowerBI-Icons/assets/78301524/92d35189-67c2-4d29-9eae-525e35d9df3e)
Experiment | experiment_preview | ![Data-Science-Experiment](https://github.com/microsoft/PowerBI-Icons/assets/78301524/91dfc564-c4e5-4bbb-9a31-8f30b60a2d39)
Event Stream | trident_artifacttype_event_stream_preview | ![Eventstream](https://github.com/microsoft/PowerBI-Icons/assets/78301524/7ee76660-7e73-4bca-b9bc-a86b58386ae1)
Kusto Database | artifact_kusto_database_preview | ![KQL Database](https://github.com/microsoft/PowerBI-Icons/assets/78301524/4d544eca-4deb-471c-b402-827574dc20c7)
Kusto Queryset | artifact_kusto_queryworkbench_preview | ![KQL Queryset](https://github.com/microsoft/PowerBI-Icons/assets/78301524/3eaa2f2a-d811-40d9-8e5e-393076a2c49b)
Model | model_preview | ![Data-Science-Model](https://github.com/microsoft/PowerBI-Icons/assets/78301524/77a60334-5aa3-4377-9fb3-6107f147b8ba)
Spark Job | trident_artifacttype_sparkjobdefinition_preview | ![Spark Job Definition](https://github.com/microsoft/PowerBI-Icons/assets/78301524/ed9a524e-dcd1-4822-994f-50b9e0026f7c)
Data Factory | product data-factory | ![DataFactory](https://github.com/microsoft/PowerBI-Icons/assets/78301524/f4c0705e-757a-4021-8015-d7698e4a409b)
Data Engineering | product data-engineering | ![Data-Engeneering](https://github.com/microsoft/PowerBI-Icons/assets/78301524/8cb2cc4a-dcad-4698-bfd7-5f7d03b6484e)
Data Science | product data-science | ![Data-Science](https://github.com/microsoft/PowerBI-Icons/assets/78301524/65a82e40-f68a-4208-ab1b-2c531bfc07cd)
Data Warehouse | product data-warehouse | ![DataWarehouse](https://github.com/microsoft/PowerBI-Icons/assets/78301524/bd8340f8-d8f8-484f-96d0-bbd543378c24)
Real-Time | product kusto | ![Real time](https://github.com/microsoft/PowerBI-Icons/assets/78301524/b97c725e-327b-4209-a778-c2fd42696934)

**Comment by tirnovar** [comment]
Also is missing icon for Domains:
Name | DataId 
---- | ------
Domain Icon |circlegroup_20_regular

**Comment by jeroenterheerdt** [comment]
Fabric icons are provided here: https://learn.microsoft.com/fabric/get-started/icons
